---
- hosts: all
  tags:
    - common
  tasks:
    - name: Update package manager cache
      action: '{{ ansible_pkg_mgr }}
        update_cache=yes
        cache_valid_time=86400' # 1 day
      sudo: yes

- include: highcore/monitoring.yml

