---
- name: Add node key to apt
  apt_key:
    id: 1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add apt repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main

- name: Install packages
  apt:
    pkg: "{{item}}"
  with_items:
    - nodejs