---
allow_duplicates: yes
dependencies:
  - role: '{{ playbook_dir }}/vendor/DavidWittman.redis'
    tags: [redis, sensu-server]
    redis_bind: localhost

  - role: '{{ playbook_dir }}/vendor/Mayeu.RabbitMQ'
    tags: [rabbitmq, sensu-server]
    rabbitmq_conf_tcp_listeners_address: '0.0.0.0' # sensu-clients will connect there
    rabbitmq_ssl: false
    rabbitmq_conf_tcp_listeners_port: "{{ monitoring_rabbitmq_port }}" #default port in Mayeu.sensu
    rabbitmq_vhost_definitions:
      - name: "{{ monitoring_rabbitmq_vhost }}"
    rabbitmq_users_definitions:
      - vhost:    "{{ monitoring_rabbitmq_vhost }}"
        user:     "{{ monitoring_rabbitmq_user }}"
        password: "{{ monitoring_rabbitmq_password }}"
        tags: ["administrator"]
    rabbitmq_plugins: ['rabbitmq_management']

  - role: '{{ playbook_dir }}/vendor/Mayeu.sensu'
    tags: [sensu, sensu-server]
    sensu_install_client: false #uchiwa and server are installed by default

    sensu_server_rabbitmq_hostname: "127.0.0.1" #we're installing both roles to the same machine here, so it's hardcoded
    sensu_server_rabbitmq_port:     "{{ monitoring_rabbitmq_port }}"
    sensu_server_rabbitmq_insecure: true
    sensu_server_rabbitmq_vhost:    "{{ monitoring_rabbitmq_vhost }}"
    sensu_server_rabbitmq_user:     "{{ monitoring_rabbitmq_user }}"
    sensu_server_rabbitmq_password: "{{ monitoring_rabbitmq_password }}"

    sensu_server_dashboard_port: "{{ monitoring_dashboard_port }}"
    sensu_server_dashboard_user: "{{ monitoring_dashboard_user }}"
    sensu_server_dashboard_password: "{{ monitoring_dashboard_password }}"

    sensu_server_api_user: "{{ monitoring_api_user }}"
    sensu_server_api_password: "{{ monitoring_api_password }}"

    sensu_checks: {}
    sensu_handlers: {} #

    sensu_settings:
      relay:
        graphite:
          host: localhost #TODO: this is going to cause trouble if\when we separate metrics-server and monitoring
          port: 2003

  - role: '{{ playbook_dir }}/roles/monitoring-client'
    tags: monitoring-client
    monitoring_hostname: "localhost"
    standalone_checks:
      test_check:
        handler   : default
        command   : "/bin/bash -c 'echo Hello World'"
        interval  : 60
        standalone: true
    system_profile: true
    client_settings:
      system_profile:
        interval: 10
        handler: 'relay'