---
allow_duplicates: yes
dependencies:
  - role: nsg.graphite
    tags: [graphite]
    graphite_secret_key: "{{ lookup('password', '/tmp/graphite_secret_key') }}"

  - role: Stouts.grafana
    tags: [grafana]
    grafana_reporting_enabled: no
    grafana_http_port: "{{ metrics_dashboard_port }}"
    grafana_secret_key: "{{ lookup('password', '/tmp/grafana_secret_key') }}"
    grafana_admin_password: "{{ metrics_admin_password }}"
    grafana_anonymous_enabled: "{{ metrics_anonymous_enabled }}"
    grafana_data: "{{ metrics_grafana_data }}"
    grafana_path: "{{ metrics_grafana_path }}"