---
- name: ensure nginx is installed
  apt: package=nginx state=installed

- name: graphite vhost
  template: src=010-graphite.conf dest=/etc/nginx/sites-available/010-graphite.conf

- name: enable graphite vhost
  file: state=link
    src=/etc/nginx/sites-available/010-graphite.conf
    dest=/etc/nginx/sites-enabled/010-graphite.conf
  notify: nginx restart

- name: setup configure graphite in grafana script
  template: src=setup-grafana.sh dest=/tmp/setup-grafana.sh mode=774

- name: graphite in grafana
  command: /tmp/setup-grafana.sh "http://localhost:{{metris_graphite_port}}"