---
- name: Install npm dependencies
  npm:
    path: '{{ ui_deploy_to }}/{{ ui_deploy_version }}'
    state: latest
  sudo_user: '{{ ui_user }}'

- name: Bower install
  command: bower install
  args:
    chdir: '{{ ui_deploy_to }}/{{ ui_deploy_version }}'
  sudo_user: '{{ ui_user }}'

- name: Grunt build
  command: grunt build
  args:
    chdir: '{{ ui_deploy_to }}/{{ ui_deploy_version }}'
  sudo_user: '{{ ui_user }}'

- name: Create upstart script
  template:
    src: upstart.j2
    dest: '/etc/init/{{ ui_app }}.conf'
    mode: 0700
  notify: restart ui

- name: Check if ssl configuration exists
  stat:
    path: "/etc/letsencrypt/live/{{ ui_domain }}/fullchain.pem"
  register: ssl_certificate_status

- name: Configure ssl
  include: ssl.yml
  when: not ssl_certificate_status.stat.exists
