---
- name: generate standalone_checks.json
  template:
    src=standalone_checks.json.j2
    dest=/etc/sensu/conf.d/standalone_checks.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify: restart sensu client

- name: generate client config
  template:
    src=client_settings.json.j2
    dest=/etc/sensu/conf.d/client_settings.json
    owner=sensu
    group=sensu
    mode=0640
  notify: restart sensu client

- name: Install git-core
  action: '{{ ansible_pkg_mgr }} pkg={{ item }}'
  with_items:
    - git-core

- name: create dirs for sensu extensions
  file: state=directory path=/etc/sensu/{{ item }} recurse=yes
  with_items:
    - extensions/checks
    - extensions/handlers
    - extensions/mutators
    - checks
    - handlers
    - mutators

- include: metrics/system_profile.yml
  when: system_profile

- include: metrics/disk_metrics.yml
  when: disk_metrics
